# Generated by Django 5.2.15 on 2026-08-19 14:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat_messages", "0010_message_sender_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROCESSING", "processing"),
                            ("COMPLETED", "completed"),
                            ("FAILED", "failed"),
                            ("QUEUED", "queued"),
                        ],
                        default="PROCESSING",
                        max_length=10,
                    ),
                ),
                (
                    "error_message",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("model", models.CharField(max_length=50)),
                (
                    "input_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_requests",
                        to="chat_messages.message",
                    ),
                ),
                (
                    "output_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_output_requests",
                        to="chat_messages.message",
                    ),
                ),
            ],
            options={
                "db_table": "ai_request",
            },
        ),
    ]
