# Generated by Django 5.2.15 on 2026-09-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_requests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PROCESSING", "processing"),
                    ("COMPLETED", "completed"),
                    ("FAILED", "failed"),
                    ("QUEUED", "queued"),
                ],
                default="QUEUED",
                max_length=10,
            ),
        ),
    ]
