# Generated by Django 5.2.15 on 2026-10-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_requests", "0002_alter_airequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="airequest",
            name="attempt_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
