# Generated by Django 5.2.15 on 2026-10-03 08:42

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_requests", "0003_airequest_attempt_count"),
        ("chat_messages", "0011_alter_message_user"),
        ("chats", "0003_chat_last_message_chat_idx_chat_activity"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=768)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_chunks",
                        to="chats.chat",
                    ),
                ),
                (
                    "end_message",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="chat_messages.message",
                    ),
                ),
                (
                    "start_message",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="chat_messages.message",
                    ),
                ),
            ],
            options={
                "db_table": "message_chunks",
                "indexes": [
                    models.Index(
                        fields=["chat", "created_at"], name="idx_chunk_chat_created"
                    )
                ],
            },
        ),
    ]
