# Generated by Django 5.1.6 on 2026-07-14 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_refreshtoken"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="account",
            table="accounts",
        ),
    ]
