"""
Constants used by the chats module
"""

# Validation field chat model constants
TYPE_MAX_LENGTH = 10
ROLE_MAX_LENGTH = 10
TITLE_MAX_LENGTH = 100
AVATAR_URL_MAX_LENGTH = 500
PRIVATE_KEY_MAX_LENGTH = 100
LIMIT_CHAT_MIN_VALUE=1
LIMIT_CHAT_MAX_VALUE=100
LIMIT_CHAT_DEFAULT_VALUE=20