# Generated by Django 5.2.15 on 2026-08-10 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("file_assets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fileasset",
            name="expires_at",
        ),
        migrations.RemoveField(
            model_name="fileasset",
            name="reference_count",
        ),
    ]
