# Generated by Django 5.1.6 on 2026-07-19 08:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chats", "0001_initial"),
        ("users", "0005_alter_user_bio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "text"),
                            ("SYSTEM", "system"),
                            ("FILE", "file"),
                            ("AI", "ai"),
                        ],
                        default="TEXT",
                        max_length=10,
                    ),
                ),
                (
                    "text_content",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chats.chat",
                    ),
                ),
                (
                    "reply_to_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="chat_messages.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "messages",
            },
        ),
    ]
