# Generated by Django 5.1.6 on 2026-07-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_messages", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="revoked_at",
            new_name="recalled_at",
        ),
        migrations.AddField(
            model_name="message",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "active"), ("RECALLED", "recalled")],
                default="ACTIVE",
                max_length=10,
            ),
        ),
    ]
