# Generated by Django 5.1.6 on 2026-07-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_messages", "0002_rename_revoked_at_message_recalled_at_message_status"),
        ("chats", "0002_chat_participants_chat_private_key"),
        ("users", "0005_alter_user_bio"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["chat", "-created_at", "-id"], name="idx_msg_chat_created_id"
            ),
        ),
    ]
