# Generated by Django 5.2.15 on 2026-08-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_messages", "0003_message_idx_msg_chat_created_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[("TEXT", "text"), ("DOCUMENT", "document")],
                default="TEXT",
                max_length=10,
            ),
        ),
    ]
