# Generated by Django 5.2.15 on 2026-08-04 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_messages", "0004_alter_message_message_type"),
        ("file_assets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentMessage",
            fields=[
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="document_message",
                        serialize=False,
                        to="chat_messages.message",
                    ),
                ),
                (
                    "file_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_message",
                        to="file_assets.fileasset",
                    ),
                ),
            ],
            options={
                "db_table": "document_message",
            },
        ),
    ]
