# Generated by Django 5.2.15 on 2026-08-08 14:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_messages", "0005_documentmessage"),
        ("file_assets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveBigIntegerField()),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_message",
                        to="file_assets.fileasset",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_message",
                        to="chat_messages.message",
                    ),
                ),
            ],
            options={
                "db_table": "image_messages",
                "ordering": ["position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("message", "position"), name="uq_image_message_position"
                    )
                ],
            },
        ),
    ]
