# Generated by Django 5.2.15 on 2026-08-10 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat_messages", "0006_imagemessage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ImageMessage",
        ),
    ]
