# Generated by Django 5.2.15 on 2026-08-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_messages", "0007_delete_imagemessage"),
        ("file_assets", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DocumentMessage",
            new_name="FileMessage",
        ),
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[("TEXT", "text"), ("FILE", "file")],
                default="TEXT",
                max_length=10,
            ),
        ),
    ]
