# Generated by Django 5.2.15 on 2026-08-10 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_messages", "0008_rename_documentmessage_filemessage_and_more"),
        ("file_assets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filemessage",
            name="file_asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="file_message",
                to="file_assets.fileasset",
            ),
        ),
        migrations.AlterField(
            model_name="filemessage",
            name="message",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="file_message",
                serialize=False,
                to="chat_messages.message",
            ),
        ),
        migrations.AlterModelTable(
            name="filemessage",
            table="file_message",
        ),
    ]
