# Generated by Django 5.2.15 on 2026-08-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_messages", "0009_alter_filemessage_file_asset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="sender_type",
            field=models.CharField(
                choices=[("USER", "user"), ("AI", "ai")], default="USER", max_length=10
            ),
        ),
    ]
