# Generated by Django 5.1.6 on 2026-07-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_participants", "0001_initial"),
        ("chats", "0001_initial"),
        ("users", "0005_alter_user_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="participants",
            field=models.ManyToManyField(
                related_name="chats",
                through="chat_participants.ChatParticipant",
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="private_key",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
