# Generated by Django 5.1.6 on 2026-07-19 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_messages", "0001_initial"),
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatparticipant",
            name="last_seen_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_seen_participants",
                to="chat_messages.message",
            ),
        ),
    ]
