# Generated by Django 5.1.6 on 2026-07-29 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_messages", "0003_message_idx_msg_chat_created_id"),
        ("chat_participants", "0002_chatparticipant_idx_cp_user_chat"),
        ("chats", "0002_chat_participants_chat_private_key"),
        ("users", "0005_alter_user_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="last_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="chat_messages.message",
            ),
        ),
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(
                fields=["-last_activity_at", "-id"], name="idx_chat_activity"
            ),
        ),
    ]
