# Generated by Django 5.1.6 on 2026-07-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0002_chatparticipant_last_seen_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="private_key",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
