# Generated by Django 5.1.6 on 2026-07-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_participants", "0001_initial"),
        ("chats", "0003_chat_private_key"),
        ("users", "0005_alter_user_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="participants",
            field=models.ManyToManyField(
                related_name="chats",
                through="chat_participants.ChatParticipant",
                to="users.user",
            ),
        ),
        migrations.DeleteModel(
            name="ChatParticipant",
        ),
    ]
