# Generated by Django 5.1.6 on 2026-07-22 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat_messages", "0001_initial"),
        ("chats", "0001_initial"),
        ("users", "0005_alter_user_bio"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("OWNER", "owner"), ("MEMBER", "member")],
                        default="MEMBER",
                        max_length=10,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_participants",
                        to="chats.chat",
                    ),
                ),
                (
                    "last_seen_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="last_seen_participants",
                        to="chat_messages.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_participants",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "chat_participants",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chat", "user"), name="uq_chat_participant"
                    )
                ],
            },
        ),
    ]
