# Generated by Django 5.1.6 on 2026-07-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_messages", "0003_message_idx_msg_chat_created_id"),
        ("chat_participants", "0001_initial"),
        ("chats", "0002_chat_participants_chat_private_key"),
        ("users", "0005_alter_user_bio"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="chatparticipant",
            index=models.Index(fields=["user", "chat"], name="idx_cp_user_chat"),
        ),
    ]
