# Generated by Django 5.1.6 on 2026-07-14 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_date_of_birth_user_dob_user_avatar_url_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
    ]
