"""
Constants used by the AI requests module
"""
STATUS_MAX_LENGTH = 10
ERROR_MESSAGE_MAX_LENGTH = 500
MODEL_MAX_LENGTH = 50

# Limit AI
DAILY_LIMIT = 20
DAILY_KEY_PREFIX = "ai:limit:daily"

# Retry
RETRY_DELAYS = (2, 5)
RETRY_ATTEMPTS = 2

# Timeout
PROVIDER_TIMEOUT = 90
CELERY_TIME_LIMIT = 100