from uuid import UUID
from pydantic import BaseModel, ConfigDict, Field

class CreateAIMessageRequest(BaseModel):
    """Request DTO for creating an AI-generated chat message"""
    model_config = ConfigDict(frozen=True)

    chat_id: UUID = Field(description="ID of the chat where the AI message will be created")
    reply_to_message: UUID = Field(description="ID of the user message that the AI message replies to")
    text_content: str = Field(description="Text content generated by the AI")